name: Test Suite

on:
  pull_request:
    branches:
      - main
      - master
      - 3.x
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and bring up Docker containers
      - name: Build and start services
        run: |
          docker compose up --build -d

      # Run tests inside the container
      - name: Run test suite
        run: |
          docker compose run app vendor/bin/phpunit --testdox

      # Bring down Docker containers after tests
      - name: Tear down services
        if: always()
        run: docker compose down
